name: fefeyo_flutter_template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  auto_route: ^10.1.0+1
  lottie: ^3.3.1
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.13

  # Platform / Device
  camera: ^0.11.2
  permission_handler: ^12.0.1
  android_intent_plus: ^5.3.1

  # Network / Serialization
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  intl: ^0.20.2

  # Env
  envied: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

  # Codegen / Generators（開発時のみ）
  build_runner: ^2.5.4
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  envied_generator: ^1.1.1
  auto_route_generator: ^10.2.3
  flutter_gen_runner: ^5.3.1

  # テスト補助（任意）
  mocktail: ^1.0.4
  riverpod_test: ^0.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/core/asset_gen/
  line_length: 80
  integrations:
    flutter_svg: true
