name: fefeyo_flutter_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  freezed: ^3.1.0
  dio: ^5.8.0+1
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  envied: ^1.1.1
  json_annotation: ^4.9.0
  auto_route: ^10.1.0+1
  freezed_annotation: ^3.1.0
  retrofit: ^4.6.0
  retrofit_generator: ^9.7.0
  fluttertoast: ^8.2.12
  camera: ^0.11.2
  permission_handler: ^12.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  speech_to_text: ^7.2.0
  lottie: ^3.3.1
  android_intent_plus: ^5.3.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.3.1
  envied_generator: ^1.1.1
  auto_route_generator: ^10.2.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/


flutter_gen:
  output: lib/core/asset_gen/
  line_length: 80
  integrations:
    flutter_svg: true
